# Generated by Django 5.1.1 on 2024-10-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id_insights', models.AutoField(primary_key=True, serialize=False)),
                ('errors_count', models.IntegerField()),
                ('hit_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
                ('insights', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_insights', to='accounts.insights')),
            ],
        ),
    ]
