# Generated by Django 5.1.1 on 2024-10-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='insights',
            new_name='id_insights',
        ),
    ]
