# Generated by Django 5.1.1 on 2024-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('total_hits', models.IntegerField()),
                ('total_errors', models.IntegerField()),
            ],
        ),
    ]
