# Generated by Django 5.1.1 on 2024-09-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_type_vocabulary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
